### ISSUE TITLE
"Lower" leaves can spawn in place of main trunk

### ISSUE THREAD

**Issue by noobanidus** [c0d3break3r/Bloomful#25] opened 2020-01-27 23:00 UTC
![](https://cdn.discordapp.com/attachments/460979039851511809/671429994727342100/unknown.png)

A check might need to be added when changing the blockstate to see if the blockstate is already a log (I'm rubbish with tree generators and last I checked everything was still obfuscated, otherwise I'd try to be more helpful with my issue, sorry!)

**Comment by fivelol** [comment] 2020-01-28 02:28
this is a duplicate of #1 I believe

**Comment by noobanidus** [comment] 2020-01-29 06:46
Ah, I didn't consider them "vines", sorry.

**Closed as completed** 2020-02-02 13:43 UTC
